[package]
name = "find_duplicates_gui"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]
edition = "2018"

[dependencies]
glib = "0.9"
gio = "0.8"
gdk = "0.12"
gtk = { version = "0.8", features = ["v3_22"] }

derive_builder = "0.9.0"
glob = "0.3.0"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
bincode = "1"
hex = "0.4"

sha2 = "0.9"
generic-array = "0.14"
lazy_static = "1"

newtype_gobject = { path = "../newtype_gobject" }
